/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripPlannerRouteImport } from './routes/trip-planner'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as MyTripsRouteImport } from './routes/my-trips'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HotPlansRouteImport } from './routes/hot-plans'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as BecomeGuideRouteImport } from './routes/become-guide'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlacesSlugRouteImport } from './routes/places.$slug'
import { Route as CitiesSlugRouteImport } from './routes/cities.$slug'
import { Route as ApiChatRouteImport } from './routes/api.chat'

const TripPlannerRoute = TripPlannerRouteImport.update({
  id: '/trip-planner',
  path: '/trip-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTripsRoute = MyTripsRouteImport.update({
  id: '/my-trips',
  path: '/my-trips',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HotPlansRoute = HotPlansRouteImport.update({
  id: '/hot-plans',
  path: '/hot-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeGuideRoute = BecomeGuideRouteImport.update({
  id: '/become-guide',
  path: '/become-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesSlugRoute = PlacesSlugRouteImport.update({
  id: '/places/$slug',
  path: '/places/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesSlugRoute = CitiesSlugRouteImport.update({
  id: '/cities/$slug',
  path: '/cities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/become-guide': typeof BecomeGuideRoute
  '/bookings': typeof BookingsRoute
  '/community': typeof CommunityRoute
  '/destinations': typeof DestinationsRoute
  '/hot-plans': typeof HotPlansRoute
  '/login': typeof LoginRoute
  '/my-trips': typeof MyTripsRoute
  '/safety': typeof SafetyRoute
  '/signup': typeof SignupRoute
  '/trip-planner': typeof TripPlannerRoute
  '/api/chat': typeof ApiChatRoute
  '/cities/$slug': typeof CitiesSlugRoute
  '/places/$slug': typeof PlacesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/become-guide': typeof BecomeGuideRoute
  '/bookings': typeof BookingsRoute
  '/community': typeof CommunityRoute
  '/destinations': typeof DestinationsRoute
  '/hot-plans': typeof HotPlansRoute
  '/login': typeof LoginRoute
  '/my-trips': typeof MyTripsRoute
  '/safety': typeof SafetyRoute
  '/signup': typeof SignupRoute
  '/trip-planner': typeof TripPlannerRoute
  '/api/chat': typeof ApiChatRoute
  '/cities/$slug': typeof CitiesSlugRoute
  '/places/$slug': typeof PlacesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/become-guide': typeof BecomeGuideRoute
  '/bookings': typeof BookingsRoute
  '/community': typeof CommunityRoute
  '/destinations': typeof DestinationsRoute
  '/hot-plans': typeof HotPlansRoute
  '/login': typeof LoginRoute
  '/my-trips': typeof MyTripsRoute
  '/safety': typeof SafetyRoute
  '/signup': typeof SignupRoute
  '/trip-planner': typeof TripPlannerRoute
  '/api/chat': typeof ApiChatRoute
  '/cities/$slug': typeof CitiesSlugRoute
  '/places/$slug': typeof PlacesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/become-guide'
    | '/bookings'
    | '/community'
    | '/destinations'
    | '/hot-plans'
    | '/login'
    | '/my-trips'
    | '/safety'
    | '/signup'
    | '/trip-planner'
    | '/api/chat'
    | '/cities/$slug'
    | '/places/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/become-guide'
    | '/bookings'
    | '/community'
    | '/destinations'
    | '/hot-plans'
    | '/login'
    | '/my-trips'
    | '/safety'
    | '/signup'
    | '/trip-planner'
    | '/api/chat'
    | '/cities/$slug'
    | '/places/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/become-guide'
    | '/bookings'
    | '/community'
    | '/destinations'
    | '/hot-plans'
    | '/login'
    | '/my-trips'
    | '/safety'
    | '/signup'
    | '/trip-planner'
    | '/api/chat'
    | '/cities/$slug'
    | '/places/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BecomeGuideRoute: typeof BecomeGuideRoute
  BookingsRoute: typeof BookingsRoute
  CommunityRoute: typeof CommunityRoute
  DestinationsRoute: typeof DestinationsRoute
  HotPlansRoute: typeof HotPlansRoute
  LoginRoute: typeof LoginRoute
  MyTripsRoute: typeof MyTripsRoute
  SafetyRoute: typeof SafetyRoute
  SignupRoute: typeof SignupRoute
  TripPlannerRoute: typeof TripPlannerRoute
  ApiChatRoute: typeof ApiChatRoute
  CitiesSlugRoute: typeof CitiesSlugRoute
  PlacesSlugRoute: typeof PlacesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trip-planner': {
      id: '/trip-planner'
      path: '/trip-planner'
      fullPath: '/trip-planner'
      preLoaderRoute: typeof TripPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-trips': {
      id: '/my-trips'
      path: '/my-trips'
      fullPath: '/my-trips'
      preLoaderRoute: typeof MyTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hot-plans': {
      id: '/hot-plans'
      path: '/hot-plans'
      fullPath: '/hot-plans'
      preLoaderRoute: typeof HotPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-guide': {
      id: '/become-guide'
      path: '/become-guide'
      fullPath: '/become-guide'
      preLoaderRoute: typeof BecomeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/$slug': {
      id: '/places/$slug'
      path: '/places/$slug'
      fullPath: '/places/$slug'
      preLoaderRoute: typeof PlacesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/$slug': {
      id: '/cities/$slug'
      path: '/cities/$slug'
      fullPath: '/cities/$slug'
      preLoaderRoute: typeof CitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BecomeGuideRoute: BecomeGuideRoute,
  BookingsRoute: BookingsRoute,
  CommunityRoute: CommunityRoute,
  DestinationsRoute: DestinationsRoute,
  HotPlansRoute: HotPlansRoute,
  LoginRoute: LoginRoute,
  MyTripsRoute: MyTripsRoute,
  SafetyRoute: SafetyRoute,
  SignupRoute: SignupRoute,
  TripPlannerRoute: TripPlannerRoute,
  ApiChatRoute: ApiChatRoute,
  CitiesSlugRoute: CitiesSlugRoute,
  PlacesSlugRoute: PlacesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
